ktor:
  application:
    modules:
      - com.mat.ApplicationKt.module
  deployment:
    port: 8080

postgres:
  url: "jdbc:postgresql://localhost:5432/tryhard"
  user: "username"
  password: "password"