name: Build and Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Adjust according to your project
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Wait for services to be healthy
        run: |
          while ! docker-compose ps | grep 'healthy'; do
            echo "Waiting for containers to be healthy...";
            sleep 5;
          done

      - name: Run tests
        run: ./gradlew test

      - name: Tear down Docker Compose
        if: always()
        run: docker-compose down
